from: default-environment-323333333333333333
server:
#测试config4
  port: 8716
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waf_6?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root1112
    password: root1111
    driverClassName: com.mysql.jdbc.Driver