server:
#测试config4
  port: 8716
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8600/eureka/
 
spring:
  application:
    name: this-server1-config
  datasource:
    url: jdbc:mysql://localhost:3306/waf_6?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver


from: default-environment-323333333333333333